plugins {
    alias(libs.plugins.android.library)
}

android {
    compileSdk = 37

    defaultConfig {
        minSdk 21

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation":
                                      "$projectDir/schemas".toString()]
            }
        }
    }

    sourceSets {
        // Adds exported schema location as test app assets.
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'm.co.rh.id.a_personal_stuff.base'
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    api libs.room.runtime
    annotationProcessor libs.room.compiler

    api libs.a.provider
    api libs.a.navigator
    api libs.a.navigator.dialog
    api libs.a.logger
    api libs.rx.utils
    api libs.rxandroid
    api libs.rxjava
    api libs.androidx.appcompat
    api libs.material
    api libs.androidx.constraintlayout
    api libs.androidx.drawerlayout
    api libs.androidx.swiperefreshlayout
    api libs.androidx.recyclerview
    api libs.androidx.exifinterface
    api libs.work.runtime

    implementation libs.photo.view
    implementation libs.concurrent.utils
    implementation libs.leakcanary.plumber

    testImplementation libs.junit
    androidTestImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.room.testing
}